### ISSUE TITLE
Script stops on error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by Willemstijn** [Willemstijn/BitcoinLottery#1]
Electrum Import Key: 5K5ZYMo49h1jjtwXuAXUv4zoKmpbSMRSkMw69A3LKRD8Mz7wBSp
Private Key: a66157873e77d171152ef22b6ef061546850f3303718b1e68ad4ce88dd12d9bd
BTC Address: 1BSZcPqwGdYBBu4bkjiT7YetRdMAFBejtC
Amount on address: 0
Electrum Import Key: 5KaJuMJtx8wGxybdbetzmGa4Tx8WJr1BFLajEykcYTZyNxrTvby
Private Key: e7a7bd0cfdb12c82f15c0f5e483860059c52d0f5e9f0e5498e759fd3d1db9372
BTC Address: 14m74JnxnRcNViyhq9DRePXx87Xft5gCKY
Traceback (most recent call last):
  File "BitcoinLottery.py", line 63, in <module>
    executeScript()
  File "BitcoinLottery.py", line 34, in executeScript
    splitter1=req.text.split(":")[2]
IndexError: list index out of range

**Comment by Willemstijn** [comment]
Regular expressions used without arrays - which caused the problem

**Comment by Willemstijn** [comment]
Regular expressions used without arrays - which caused the problem
