### ISSUE TITLE
Script stops with error: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Willemstijn** [Willemstijn/BitcoinLottery#2]
Traceback (most recent call last):
  File "./BitcoinLottery.py", line 86, in <module>
    executeScript()
  File "./BitcoinLottery.py", line 46, in executeScript
    btcamountinteger = int(btcamount)
ValueError: invalid literal for int() with base 10: 'no balance found'

**Comment by Willemstijn** [comment]
The int() method does not allow you to pass a float represented as a string. If you try to convert any string value not formatted as an integer, this error is raised.
See: https://careerkarma.com/blog/python-valueerror-invalid-literal-for-int-with-base-10/
